### ISSUE TITLE
Allure 2.13.6.4 and above outputs hash instead of json

### ISSUE THREAD

**Issue by naoya7076** [allure-framework/allure-ruby#335] opened 2021-12-17 02:57 UTC
Hello!

when allure-rspec is 2.13.6.3 or before
at `Gemfile`:
`gem 'allure-rspec', '= 2.13.6.3'`
`gem 'allure-ruby-commons', '= 2.13.6.3'`

at `spec_helper.rb`:
```
require 'allure-rspec'
Allure.configure do |config|
  config.results_directory = ALLURE_RESULTS_PATH
  config.clean_results_directory = true
  config.logging_level = Logger::INFO
end

RSpec.configure do |config|
	config.formatter = AllureRspecFormatter
```

allure-results file format is json and allure report displays correctly
```
{"name":"test_name","children":["e5c50e10-ec52-0139-2ffd-2cde48001122"],"befores":[],"afters":[],"links":[],"start":1630391445856,"stop":1630391454280}
```

I try to update 2.13.6.4
at `Gemfile`:
`gem 'allure-rspec', '= 2.13.6.4'`
`gem 'allure-ruby-commons', '= 2.13.6.4'`

allure-results file become to hash
`"#<Allure::TestResult:0x00007fcd31cc6bf8>"`

and allure report does not display correctly
![image](https://user-images.githubusercontent.com/32981554/146481680-af01a953-a5cd-4d8d-9315-0640fa64fa81.png)

When allure-rspec version is 2.15.0, allure-results file is also hash format.

Is there a way to output json?

**Comment by naoya7076** [comment] 2021-12-17 02:57
I think [this PR](https://github.com/allure-framework/allure-ruby/pull/175) is a cause.

**Comment by andrcuns** [comment] 2021-12-17 09:12
Do you have an example repo how to reproduce this issue maybe?

This project builds the report for itself using latest version and numerous others and all of them work just fine: https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/heads/master/index.html

**Comment by naoya7076** [comment] 2022-01-06 02:03
Thanks, I cloned `allure-test-reports` and confirmed to work fine.
Unfortunately, this issue occurred in a private repository. I tried to extract minimum example but I could not reproduce this issue.

**Comment by naoya7076** [comment] 2022-01-06 02:16
I know two solutions.

1. Change Oj.default_options of allure_ruby_commons.
From `use_to_hash: true` to `use_to_json: true`
https://github.com/allure-framework/allure-ruby/blob/b858d150a79f44cb7d81e01528039be84b73bd37/allure-ruby-commons/lib/allure_ruby_commons/model/01_jsonable.rb#L8

2.  Rewrite Oj option in spec_helper.rb
In spec_helper.rb
```
require 'oj'

Oj.default_options = { mode: :custom, use_to_json: true, ascii_only: true }
```

I  hope these help the people faces same issue.

**Comment by andrcuns** [comment] 2022-01-06 17:01
@naoya7076 I suspect this might happen if the project in question already uses Oj and maybe somehow modifies the options so it changes the default behaviour globally.

I will see if we can pass options explicitly where the jsons are generated or maybe not use Oj all together. I will need to measure if it actually adds performance benefits or not.

**Comment by andrcuns** [comment] 2022-03-08 22:22
I will close this issue since #354 has been released. Hopefully it improves behaviour for projects that already use Oj.

I still have no idea how proposed solution could have fixed the problem, because changing `use_to_hash` to `use_to_json` brakes tests in this repo and doesn't produce valid json files. It must be something project specific.

**Closed by andrcuns** 2022-03-08 22:22 UTC
Labels: type:bug

**Comment by naoya7076** [comment] 2022-04-28 07:43
Thanks @andrcuns ! Checked latest allure works fine and an allure report displays correctly!
